print ("Taukhid Aji Nurwijayadi\n")
# Komentar atau ctrl + /


"""
INI ADALAH KOMENTAR MULTILINE
INI ADALAH KOMENTAR MULTILINE
INI ADALAH KOMENTAR MULTILINE
INI ADALAH KOMENTAR MULTILINE
INI ADALAH KOMENTAR MULTILINE
"""